class Celular():
#[PROPIEDAD = "VALOR"]
    marca = "Samsung"
    modelo = "s23"
    camara = "48MP"

#LOS OBJETOS SON UNA INSTANCIA DE UNA CLASE
Celular1 = Celular() #CELULAR1 ES UNA INSTANCIA DE LA CLASE CELULAR ES DECIR ES UN OBJETO
Celular2 = Celular() #CELULAR2 ES UN OBJETO
Celular3 = Celular() #CELULAR3 ES UN OBJETO
Celular4 = Celular() #CELULAR4 ES UN OBJETO
#AL CREAR UN OBJETO SU INFORMACION SE ALMMACENA EN LA RAM

#EL OBJETO VA A MOSTRAR LAS PROPIEDADES QUE ESPECIFICAMOS EN LA CLASE, LAS CUALES SON ATRIBUTOS ESTATICOS 
print(Celular2.camara)